Siganushka\PaymentBundle\Entity\PaymentRefund:
    attributes:
        number:
            groups: [payment.item, payment.collection, payment_refund.item]
        amount:
            groups: [payment.item, payment.collection, payment_refund.item]
        successful:
            groups: [payment.item, payment.collection, payment_refund.item]
        failedReason:
            groups: [payment.item, payment.collection, payment_refund.item]
        note:
            groups: [payment.item, payment.collection, payment_refund.item]
        createdAt:
            groups: [payment.item, payment.collection, payment_refund.item]
        updatedAt:
            groups: [payment.item, payment.collection, payment_refund.item]
