Siganushka\PaymentBundle\Entity\AbstractPaymentRefund:
    properties:
        amount:
            - NotBlank: ~
            - GreaterThan: { value: 0 }
            - LessThanOrEqual: { propertyPath: payment?.refundableAmount }
        note:
            - Length: { max: 32 }
